### ISSUE TITLE
Add API detail page to hub

### ISSUE THREAD

**Issue by darosh** [darosh/angular-swagger-ui-material#10]
Brainstorming ideas:
- show all metadata, probably json only to keep it simple
- some standard metadata could look like metadata list with icons in material ui
- version switch, tabs or select/option
- preview json/yaml
- link to github file
- download json/yaml (links moved from hub cards, maybe <a download="...">)
- open in
  - material ui
  - swagger ui 
  - swagger editor
  - postman button? https://www.getpostman.com/docs/run_button
- validator badge
- disqus or g+ comments widget?
- SO link with prefilled tags? http://stackoverflow.com/questions/ask?tags=swagger+api+trello.com

@IvanGoncharov  any other ideas?

**Comment by IvanGoncharov** [comment]
@darosh Link to swagger-diff demo to compare different version of the same API.
This is example for Google Drive API:
https://zallek.github.io/swagger-diff/?oldSpecUrl=https%3A%2F%2Fapis-guru.github.io%2Fapi-models%2Fgoogleapis.com%2Fdrive%2Fv2%2Fswagger.yaml&newSpecUrl=https%3A%2F%2Fapis-guru.github.io%2Fapi-models%2Fgoogleapis.com%2Fdrive%2Fv3%2Fswagger.yaml

**Comment by darosh** [comment]
@IvanGoncharov diff looks useful, thanks!

**Comment by IvanGoncharov** [comment]
> link to github file

I think it's a bad idea.
The file structure in APIs.guru repo can change in future.
It already happened ones: https://github.com/APIs-guru/api-models/issues/19
And could happen in future.

But API is stable from day one and will stay so in future.

**Comment by darosh** [comment]
@IvanGoncharov thanks for your comments. I sometimes look at the patch file so I will keep the link, at least for the time being.

http://darosh.github.io/angular-swagger-ui-material/hub/#/googleapis.com:analytics
![capture](https://cloud.githubusercontent.com/assets/297320/13731445/f2e3fc20-e968-11e5-94d9-a7cf004b4ba2.PNG)

**Comment by darosh** [comment]
Closing with leftovers: SO link and Postman button (which probably needs collection shared in the cloud).
