### ISSUE TITLE
Hub: display APIs.guru vendor extensions

### ISSUE THREAD

**Issue by IvanGoncharov** [darosh/angular-swagger-ui-material#12]
You can add `x-apiClientRegistration` it links to a page where you can get API key.
Not all APIs currently have it, but I try to add it for all new APIs.

Also `x-unofficialSpec` pretty important it's mean that this spec is not from official source.

This is more advanced by you can use `x-providerName` to group APIs.

**Comment by darosh** [comment]
@IvanGoncharov thanks for suggestions!
- [x] apiClientRegistration added to hub already (it is in the Versions card)
- [x] apiClientRegistration added to Material Swagger UI
- [x] unofficialSpec added (did not know about that)
- [x] grouping is interesting idea, try the folder button http://darosh.github.io/angular-swagger-ui-material/hub/#?group

**Comment by darosh** [comment]
@IvanGoncharov added [grouped groups only](http://darosh.github.io/angular-swagger-ui-material/hub/#?search=:&group) to search examples
