### ISSUE TITLE
Tested on APIs.guru badge

### ISSUE THREAD

**Issue by IvanGoncharov** [darosh/angular-swagger-ui-material#13]
I added badge [![Tested on APIs.guru](http://apis-guru.github.io/api-models/banners/tested_on_banner.svg)](https://github.com/APIs-guru/api-models)
You can use it in your readme, just add following:

```
[![Tested on APIs.guru](http://apis-guru.github.io/api-models/banners/tested_on_banner.svg)](https://github.com/APIs-guru/api-models)
```

**Comment by darosh** [comment]
@IvanGoncharov Sorry for late response. The badge URL http://apis-guru.github.io/api-models/banners/tested_on_banner.svg does not work.

**Comment by IvanGoncharov** [comment]
@darosh It was moved to different hosting same time as our API.
New location is: 
[![Tested on APIs.guru](http://api.apis.guru/badges/tested_on.svg)](https://github.com/APIs-guru/openapi-directory)

```
[![Tested on APIs.guru](http://api.apis.guru/badges/tested_on.svg)](https://github.com/APIs-guru/openapi-directory)
```

**Comment by darosh** [comment]
@IvanGoncharov thx, just a little question: the badge shows "359 specs", but the https://api.apis.guru/v2/list.json has only 280 keys, does the 359 number inludes some revisons or what?

**Comment by darosh** [comment]
@IvanGoncharov ...also I cannot guarantee always up to date testing, so probably just https://img.shields.io/badge/tested%20on-apis.guru%20specs-green.svg could be a good compromise, what do you think?

**Comment by IvanGoncharov** [comment]
@darosh On the top level, you have one key per API. But Google and Microsoft have multiple versions of some APIs.

**Comment by IvanGoncharov** [comment]
> also I cannot guarantee always up to date testing

@darosh You not running nuclear power plant :) so no one demand 100% correctness 24/7.
But it's your decision as the author. 
Just change `apis.guru` to `APIs.guru`:
https://img.shields.io/badge/tested%20on-APIs.guru%20specs-green.svg

**Comment by darosh** [comment]
@IvanGoncharov ok, right, I am not power planted (yet :), but no false promises needed too, the test suite is based on your list and that fact (same as the list) is great anyway :) see the README updated: https://github.com/darosh/angular-swagger-ui-material/blob/master/README.md OK?

**Comment by IvanGoncharov** [comment]
@darosh 👍
