### ISSUE TITLE
Adding to APIs.guru's integrations list.

### ISSUE THREAD

**Issue by IvanGoncharov** [darosh/angular-swagger-ui-material#3]
Your Hub looks very promising and I like to add it into this list:
https://github.com/APIs-guru/api-models#existing-integrations
If you agree, just send me PR or write here description for Hub page.
Note: I add integrations to the list in chronological order.

**Comment by darosh** [comment]
@IvanGoncharov  thanks for your kind feedback, this project is pretty young (2 weeks) let's wait for more mature and stable release, for example the filters could be confusing without description:

![image](https://cloud.githubusercontent.com/assets/297320/13569941/7d196dba-e46b-11e5-87a7-b9ede9742385.png)

**Comment by darosh** [comment]
@IvanGoncharov hub is redesigned and moved to new location: https://darosh.github.io/angular-swagger-ui-material/hub/ it has some new features (bookmarkable search/filter/sort) and shows more metadata - feel free to add it to the integration list. Description could be `testing and exploring hub for Material Swagger UI demo` ...or whatever you pick. Although the Material UI is not finished yet the hub could be useful for someone already. Thanks!

**Comment by IvanGoncharov** [comment]
@darosh Done.
